const PROBLEM_PACK = {
  name: '다각형의 둘레와 넓이',
  emoji: '📐',
  description: '둘레·넓이 공식, 넓이 단위 변환, 도형 문장제',
  enemies: [
    { emoji: '🐸', name: '개구리', hp: 100 },
    { emoji: '🦝', name: '너구리', hp: 130 },
    { emoji: '🐺', name: '늑대', hp: 160 },
    { emoji: '🦊', name: '구미호', hp: 190 },
    { emoji: '🐉', name: '드래곤', hp: 220 },
  ],
  problems: [

    // ════════════════════════════════════════════════════
    // 브론즈: 기초 개념과 단순 계산 (75문제)
    // ════════════════════════════════════════════════════

    // ── 다각형의 둘레 구하기 ──
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정삼각형은 세 변의 길이가 모두 같아요. 4 × 3을 계산해요.', text: '한 변이 4cm인 정삼각형의 둘레는 몇 cm인가요?', answer: '12' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정삼각형의 둘레 = 한 변 × 3이에요.', text: '한 변이 5cm인 정삼각형의 둘레는 몇 cm인가요?', answer: '15' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정삼각형의 둘레 = 한 변 × 3이에요.', text: '한 변이 7cm인 정삼각형의 둘레는 몇 cm인가요?', answer: '21' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정삼각형의 둘레 = 한 변 × 3이에요.', text: '한 변이 9cm인 정삼각형의 둘레는 몇 cm인가요?', answer: '27' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정삼각형의 둘레 = 한 변 × 3이에요.', text: '한 변이 11cm인 정삼각형의 둘레는 몇 cm인가요?', answer: '33' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '직사각형의 둘레 = (가로 + 세로) × 2예요. (7+3)×2를 계산해요.', text: '가로 7cm, 세로 3cm인 직사각형의 둘레는 몇 cm인가요?', answer: '20' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '직사각형의 둘레 = (가로 + 세로) × 2예요.', text: '가로 8cm, 세로 5cm인 직사각형의 둘레는 몇 cm인가요?', answer: '26' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '직사각형의 둘레 = (가로 + 세로) × 2예요.', text: '가로 10cm, 세로 4cm인 직사각형의 둘레는 몇 cm인가요?', answer: '28' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '직사각형의 둘레 = (가로 + 세로) × 2예요.', text: '가로 11cm, 세로 6cm인 직사각형의 둘레는 몇 cm인가요?', answer: '34' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '직사각형의 둘레 = (가로 + 세로) × 2예요.', text: '가로 12cm, 세로 3cm인 직사각형의 둘레는 몇 cm인가요?', answer: '30' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정사각형의 둘레 = 한 변 × 4예요.', text: '한 변이 5cm인 정사각형의 둘레는 몇 cm인가요?', answer: '20' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정사각형의 둘레 = 한 변 × 4예요.', text: '한 변이 6cm인 정사각형의 둘레는 몇 cm인가요?', answer: '24' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정사각형의 둘레 = 한 변 × 4예요.', text: '한 변이 8cm인 정사각형의 둘레는 몇 cm인가요?', answer: '32' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정사각형의 둘레 = 한 변 × 4예요.', text: '한 변이 10cm인 정사각형의 둘레는 몇 cm인가요?', answer: '40' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정사각형의 둘레 = 한 변 × 4예요.', text: '한 변이 12cm인 정사각형의 둘레는 몇 cm인가요?', answer: '48' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정오각형은 다섯 변의 길이가 모두 같아요. 한 변 × 5를 계산해요.', text: '한 변이 5cm인 정오각형의 둘레는 몇 cm인가요?', answer: '25' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정오각형의 둘레 = 한 변 × 5예요.', text: '한 변이 8cm인 정오각형의 둘레는 몇 cm인가요?', answer: '40' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정육각형은 여섯 변의 길이가 모두 같아요. 한 변 × 6을 계산해요.', text: '한 변이 4cm인 정육각형의 둘레는 몇 cm인가요?', answer: '24' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '정육각형의 둘레 = 한 변 × 6이에요.', text: '한 변이 5cm인 정육각형의 둘레는 몇 cm인가요?', answer: '30' },
    { difficulty: 'easy', topic: '다각형의 둘레', hint: '마름모는 네 변의 길이가 모두 같아요. 한 변 × 4를 계산해요.', text: '한 변이 9cm인 마름모의 둘레는 몇 cm인가요?', answer: '36' },

    // ── 제곱센티미터 알아보기 ──
    { difficulty: 'easy', topic: '제곱센티미터', hint: '한 변이 1cm인 정사각형의 넓이를 1cm²(1제곱센티미터)라고 해요.', text: '가로 1cm, 세로 1cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '1', choices: ['1', '2', '4', '0.5'] },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '1cm² 단위 정사각형이 가로로 4개, 세로로 3줄 있어요. 4 × 3을 계산해요.', text: '가로 4cm, 세로 3cm인 직사각형 안에 1cm² 단위 정사각형이 몇 개 들어가나요?', answer: '12', choices: ['12', '14', '7', '10'] },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 5cm, 세로 2cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '10' },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 3cm, 세로 3cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '9' },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 6cm, 세로 2cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '12' },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 4cm, 세로 4cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '16' },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 2cm, 세로 7cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '14' },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 5cm, 세로 5cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '25' },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '1cm² 단위 정사각형이 가로 8개, 세로 2줄이에요. 8 × 2를 계산해요.', text: '가로 8cm, 세로 2cm인 직사각형 안에 1cm² 단위 정사각형이 몇 개 들어가나요?', answer: '16', choices: ['16', '20', '10', '8'] },
    { difficulty: 'easy', topic: '제곱센티미터', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 3cm, 세로 6cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '18' },

    // ── 직사각형의 넓이 구하기 ──
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 6cm, 세로 4cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '24' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 9cm, 세로 5cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '45' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 8cm, 세로 7cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '56' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 3cm, 세로 11cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '33' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 7cm, 세로 6cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '42' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 4cm, 세로 12cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '48' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 2cm, 세로 15cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '30' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 10cm, 세로 6cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '60' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 13cm, 세로 4cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '52' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 14cm, 세로 5cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '70' },

    // ── 정사각형의 넓이 구하기 ──
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 3cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '9' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 4cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '16' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 5cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '25' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 6cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '36' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 7cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '49' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 8cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '64' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 9cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '81' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 10cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '100' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 11cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '121' },

    // ── 둘레에서 변의 길이 구하기 (기초 역산) ──
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '정사각형의 둘레 = 한 변 × 4이므로, 한 변 = 둘레 ÷ 4예요.', text: '둘레가 16cm인 정사각형의 한 변의 길이는 몇 cm인가요?', answer: '4' },
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '정사각형 한 변 = 둘레 ÷ 4예요.', text: '둘레가 20cm인 정사각형의 한 변의 길이는 몇 cm인가요?', answer: '5' },
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '정사각형 한 변 = 둘레 ÷ 4예요.', text: '둘레가 28cm인 정사각형의 한 변의 길이는 몇 cm인가요?', answer: '7' },
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '정삼각형의 둘레 = 한 변 × 3이므로, 한 변 = 둘레 ÷ 3이에요.', text: '둘레가 18cm인 정삼각형의 한 변의 길이는 몇 cm인가요?', answer: '6' },
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '정삼각형 한 변 = 둘레 ÷ 3이에요.', text: '둘레가 24cm인 정삼각형의 한 변의 길이는 몇 cm인가요?', answer: '8' },
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '직사각형 둘레 = (가로+세로)×2. 세로 = 둘레÷2 - 가로예요.', text: '둘레가 20cm이고 가로가 6cm인 직사각형의 세로는 몇 cm인가요?', answer: '4' },
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '직사각형 둘레 ÷ 2에서 한쪽 변을 빼면 나머지 변이 나와요.', text: '둘레가 30cm이고 가로가 9cm인 직사각형의 세로는 몇 cm인가요?', answer: '6' },
    { difficulty: 'easy', topic: '둘레와 변의 길이', hint: '정오각형 한 변 = 둘레 ÷ 5예요.', text: '둘레가 35cm인 정오각형의 한 변의 길이는 몇 cm인가요?', answer: '7' },

    // ── 넓이에서 변의 길이 구하기 (기초) ──
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '직사각형 넓이 = 가로 × 세로이므로, 세로 = 넓이 ÷ 가로예요.', text: '넓이가 24cm²이고 가로가 6cm인 직사각형의 세로는 몇 cm인가요?', answer: '4' },
    { difficulty: 'easy', topic: '직사각형의 넓이', hint: '세로 = 넓이 ÷ 가로예요.', text: '넓이가 35cm²이고 가로가 7cm인 직사각형의 세로는 몇 cm인가요?', answer: '5' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '정사각형 넓이 = 한 변 × 한 변. □×□=25를 만족하는 □를 구해요.', text: '넓이가 25cm²인 정사각형의 한 변의 길이는 몇 cm인가요?', answer: '5' },
    { difficulty: 'easy', topic: '정사각형의 넓이', hint: '□×□=36을 만족하는 □를 구해요.', text: '넓이가 36cm²인 정사각형의 한 변의 길이는 몇 cm인가요?', answer: '6' },

    // ── 쉬운 문장제 ──
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '색종이의 가로가 10cm, 세로가 8cm예요. 이 색종이의 넓이는 몇 cm²인가요?', answer: '80' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '공책의 가로가 21cm, 세로가 15cm예요. 공책 한 면의 넓이는 몇 cm²인가요?', answer: '315' },
    { difficulty: 'easy', topic: '문장제', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 25cm인 정사각형 모양의 손수건이 있어요. 이 손수건의 넓이는 몇 cm²인가요?', answer: '625' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 5m, 세로 3m인 직사각형 모양의 화단이 있어요. 이 화단의 넓이는 몇 m²인가요?', answer: '15' },
    { difficulty: 'easy', topic: '문장제', hint: '정사각형의 둘레 = 한 변 × 4예요.', text: '한 변이 8m인 정사각형 모양의 마당이 있어요. 이 마당의 둘레는 몇 m인가요?', answer: '32' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '교실의 가로가 9m, 세로가 7m예요. 교실 바닥의 넓이는 몇 m²인가요?', answer: '63' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '게시판의 가로가 120cm, 세로가 90cm예요. 게시판의 넓이는 몇 cm²인가요?', answer: '10800' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 4m, 세로 6m인 직사각형 모양의 화단이 있어요. 이 화단의 넓이는 몇 m²인가요?', answer: '24' },
    { difficulty: 'easy', topic: '문장제', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 30cm인 정사각형 모양의 타일이 있어요. 이 타일의 넓이는 몇 cm²인가요?', answer: '900' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '수건의 가로가 50cm, 세로가 30cm예요. 이 수건의 넓이는 몇 cm²인가요?', answer: '1500' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '창문의 가로가 80cm, 세로가 60cm예요. 이 창문의 넓이는 몇 cm²인가요?', answer: '4800' },
    { difficulty: 'easy', topic: '문장제', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 20cm인 정사각형 모양의 마루 타일이 있어요. 이 타일의 넓이는 몇 cm²인가요?', answer: '400' },
    { difficulty: 'easy', topic: '문장제', hint: '직사각형의 둘레 = (가로 + 세로) × 2예요.', text: '가로 15cm, 세로 9cm인 직사각형 모양의 그림 액자가 있어요. 이 액자의 둘레는 몇 cm인가요?', answer: '48' },

    // ════════════════════════════════════════════════════
    // 실버: 다양한 넓이 공식 + 단위 변환 (120문제)
    // ════════════════════════════════════════════════════

    // ── 평행사변형의 넓이 ──
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요. 기울어진 빗변이 아닌 수직 높이를 써요.', text: '밑변이 8cm, 높이가 5cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '40' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 6cm, 높이가 7cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '42' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 12cm, 높이가 4cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '48' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 9cm, 높이가 6cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '54' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 10cm, 높이가 3cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '30' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 7cm, 높이가 8cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '56' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 15cm, 높이가 4cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '60' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 11cm, 높이가 5cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '55' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 13cm, 높이가 6cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '78' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 20cm, 높이가 7cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '140' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 14cm, 높이가 3cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '42' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 16cm, 높이가 5cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '80' },

    // ── 삼각형의 넓이 ──
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형 2개를 붙이면 평행사변형이 돼요. 삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 6cm, 높이가 4cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '12' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 10cm, 높이가 8cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '40' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 7cm, 높이가 6cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '21' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요. 마지막에 ÷2를 꼭 해요.', text: '밑변이 9cm, 높이가 4cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '18', choices: ['18', '36', '13', '26'] },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 12cm, 높이가 5cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '30' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 8cm, 높이가 9cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '36' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 14cm, 높이가 6cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '42' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 11cm, 높이가 4cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '22' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 15cm, 높이가 8cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '60' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 5cm, 높이가 10cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '25' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 13cm, 높이가 4cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '26' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 18cm, 높이가 5cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '45' },

    // ── 마름모의 넓이 ──
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 6cm, 8cm인 마름모의 넓이는 몇 cm²인가요?', answer: '24' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 10cm, 4cm인 마름모의 넓이는 몇 cm²인가요?', answer: '20' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요. ÷2를 잊지 마세요!', text: '두 대각선의 길이가 각각 9cm, 6cm인 마름모의 넓이는 몇 cm²인가요?', answer: '27', choices: ['27', '54', '30', '15'] },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 12cm, 5cm인 마름모의 넓이는 몇 cm²인가요?', answer: '30' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 8cm, 10cm인 마름모의 넓이는 몇 cm²인가요?', answer: '40' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 14cm, 6cm인 마름모의 넓이는 몇 cm²인가요?', answer: '42' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 7cm, 8cm인 마름모의 넓이는 몇 cm²인가요?', answer: '28' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 16cm, 4cm인 마름모의 넓이는 몇 cm²인가요?', answer: '32' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 10cm, 12cm인 마름모의 넓이는 몇 cm²인가요?', answer: '60' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 9cm, 8cm인 마름모의 넓이는 몇 cm²인가요?', answer: '36' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 15cm, 6cm인 마름모의 넓이는 몇 cm²인가요?', answer: '45' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 11cm, 10cm인 마름모의 넓이는 몇 cm²인가요?', answer: '55' },

    // ── 사다리꼴의 넓이 ──
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요. 먼저 윗변과 아랫변을 더해요.', text: '윗변 3cm, 아랫변 7cm, 높이 4cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '20' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 5cm, 아랫변 9cm, 높이 6cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '42' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '(윗변+아랫변)을 먼저 더하고 높이를 곱한 뒤 2로 나눠요.', text: '윗변 4cm, 아랫변 8cm, 높이 5cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '30', choices: ['30', '60', '40', '24'] },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 6cm, 아랫변 10cm, 높이 7cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '56' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 2cm, 아랫변 8cm, 높이 5cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '25' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 3cm, 아랫변 9cm, 높이 4cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '24' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 7cm, 아랫변 11cm, 높이 6cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '54' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 4cm, 아랫변 6cm, 높이 8cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '40' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 5cm, 아랫변 15cm, 높이 6cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '60' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 8cm, 아랫변 12cm, 높이 5cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '50' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 2cm, 아랫변 6cm, 높이 9cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '36' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 10cm, 아랫변 14cm, 높이 4cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '48' },

    // ── 넓이 단위 변환(m², km²) ──
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1m = 100cm이므로 1m² = 100 × 100 = 10000cm²예요.', text: '1m²는 몇 cm²인가요?', answer: '10000', choices: ['10000', '1000', '100', '100000'] },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1m² = 10000cm²이므로 2m² = 2 × 10000이에요.', text: '2m²는 몇 cm²인가요?', answer: '20000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1m² = 10000cm²이므로 4m² = 4 × 10000이에요.', text: '4m²는 몇 cm²인가요?', answer: '40000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1m² = 10000cm²이므로 5m² = 5 × 10000이에요.', text: '5m²는 몇 cm²인가요?', answer: '50000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1m² = 10000cm²이므로 7m² = 7 × 10000이에요.', text: '7m²는 몇 cm²인가요?', answer: '70000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1m² = 10000cm²이므로 10m² = 10 × 10000이에요.', text: '10m²는 몇 cm²인가요?', answer: '100000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: 'cm²를 m²로 바꿀 때는 10000으로 나눠요. 20000 ÷ 10000 = ?', text: '20000cm²는 몇 m²인가요?', answer: '2' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '30000 ÷ 10000 = ?', text: '30000cm²는 몇 m²인가요?', answer: '3' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '80000 ÷ 10000 = ?', text: '80000cm²는 몇 m²인가요?', answer: '8' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '50000 ÷ 10000 = ?', text: '50000cm²는 몇 m²인가요?', answer: '5' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1km = 1000m이므로 1km² = 1000 × 1000 = 1000000m²예요.', text: '1km²는 몇 m²인가요?', answer: '1000000', choices: ['1000000', '100000', '10000', '10000000'] },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1km² = 1000000m²이므로 2km² = 2 × 1000000이에요.', text: '2km²는 몇 m²인가요?', answer: '2000000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1km² = 1000000m²이므로 3km² = 3 × 1000000이에요.', text: '3km²는 몇 m²인가요?', answer: '3000000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '1km² = 1000000m²이므로 5km² = 5 × 1000000이에요.', text: '5km²는 몇 m²인가요?', answer: '5000000' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: 'm²를 km²로 바꿀 때는 1000000으로 나눠요.', text: '2000000m²는 몇 km²인가요?', answer: '2' },
    { difficulty: 'normal', topic: '넓이 단위 변환', hint: '4000000 ÷ 1000000 = ?', text: '4000000m²는 몇 km²인가요?', answer: '4' },

    // ── 넓이에 알맞은 단위 ──
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '교실처럼 사람이 생활하는 공간의 넓이는 m²(제곱미터)로 나타내요.', text: '교실 바닥의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'm²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '나라나 도시처럼 아주 넓은 곳의 넓이는 km²(제곱킬로미터)로 나타내요.', text: '우리나라 국토의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'km²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '손바닥이나 지우개처럼 작은 물건의 넓이는 cm²(제곱센티미터)로 나타내요.', text: '지우개 한 면의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'cm²', choices: ['cm²', 'm²', 'km²', 'dm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '운동장은 사람이 뛰어다닐 만큼 넓어요. m²(제곱미터)가 알맞아요.', text: '학교 운동장의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'm²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '우표는 손가락 크기만큼 작아요. cm²(제곱센티미터)가 알맞아요.', text: '우표 한 면의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'cm²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '축구장은 m²(제곱미터)로 나타내요.', text: '축구장의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'm²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '서울시처럼 도시의 넓이는 km²(제곱킬로미터)로 나타내요.', text: '서울시의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'km²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '노트는 손으로 잡는 크기예요. cm²(제곱센티미터)가 알맞아요.', text: '공책 한 면의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'cm²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '공원은 m²(제곱미터)로 나타내요.', text: '마을 공원의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'm²', choices: ['cm²', 'm²', 'km²', 'mm²'] },
    { difficulty: 'normal', topic: '알맞은 넓이 단위', hint: '제주도처럼 큰 섬의 넓이는 km²(제곱킬로미터)로 나타내요.', text: '제주도의 넓이를 나타낼 때 가장 알맞은 단위는 무엇인가요?', answer: 'km²', choices: ['cm²', 'm²', 'km²', 'mm²'] },

    // ── 오류 찾기 ──
    { difficulty: 'normal', topic: '오류 찾기', hint: '삼각형의 넓이는 밑변 × 높이를 구한 뒤 반드시 2로 나눠야 해요.', text: '밑변 8cm, 높이 5cm인 삼각형의 넓이를 "8 × 5 = 40cm²"라고 했어요. 어디서 틀렸나요?', answer: '2로 나누지 않았음', choices: ['2로 나누지 않았음', '밑변을 잘못 사용했음', '높이를 잘못 사용했음', '단위가 틀렸음'] },
    { difficulty: 'normal', topic: '오류 찾기', hint: '마름모의 넓이 공식은 두 대각선의 곱 ÷ 2예요. 더하기가 아니에요.', text: '두 대각선이 6cm, 8cm인 마름모의 넓이를 "(6 + 8) ÷ 2 = 7cm²"라고 했어요. 무엇이 틀렸나요?', answer: '대각선의 합이 아닌 곱을 해야 함', choices: ['대각선의 합이 아닌 곱을 해야 함', '2로 나누면 안 됨', '대각선 중 하나만 써야 함', '단위가 틀렸음'] },
    { difficulty: 'normal', topic: '오류 찾기', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요. 마지막에 ÷2가 필요해요.', text: '윗변 4cm, 아랫변 8cm, 높이 5cm인 사다리꼴의 넓이를 "(4+8)×5 = 60cm²"라고 했어요. 무엇이 틀렸나요?', answer: '2로 나누지 않았음', choices: ['2로 나누지 않았음', '윗변과 아랫변을 더하면 안 됨', '높이가 틀렸음', '단위가 틀렸음'] },
    { difficulty: 'normal', topic: '오류 찾기', hint: '평행사변형의 넓이 = 밑변 × 높이예요. 기울어진 빗변이 아닌 수직 높이를 써야 해요.', text: '평행사변형의 넓이를 밑변 × 빗변으로 계산했어요. 무엇이 잘못되었나요?', answer: '빗변이 아닌 수직 높이를 써야 함', choices: ['빗변이 아닌 수직 높이를 써야 함', '밑변이 아닌 윗변을 써야 함', '2로 나눠야 함', '단위가 틀렸음'] },
    { difficulty: 'normal', topic: '오류 찾기', hint: '정사각형의 둘레 = 한 변 × 4예요. 넓이 공식(한 변 × 한 변)과 혼동하지 마세요.', text: '한 변이 6cm인 정사각형의 둘레를 "6 × 6 = 36cm"라고 했어요. 무엇이 잘못되었나요?', answer: '한 변 × 4를 해야 함', choices: ['한 변 × 4를 해야 함', '한 변 × 3을 해야 함', '한 변 × 2를 해야 함', '단위가 틀렸음'] },
    { difficulty: 'normal', topic: '오류 찾기', hint: '직사각형의 둘레 = (가로 + 세로) × 2예요. 가로 × 세로는 넓이 공식이에요.', text: '가로 7cm, 세로 4cm인 직사각형의 둘레를 "7 × 4 = 28cm"라고 했어요. 무엇이 잘못되었나요?', answer: '(가로+세로)×2를 해야 함', choices: ['(가로+세로)×2를 해야 함', '가로+세로만 해야 함', '÷2를 해야 함', '단위가 틀렸음'] },

    // ── 실버급 문장제 ──
    { difficulty: 'normal', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 10m, 세로 8m인 직사각형 모양의 화단이 있어요. 이 화단의 넓이는 몇 m²인가요?', answer: '80' },
    { difficulty: 'normal', topic: '문장제', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 14m, 높이가 6m인 삼각형 모양의 공원이 있어요. 이 공원의 넓이는 몇 m²인가요?', answer: '42' },
    { difficulty: 'normal', topic: '문장제', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 25m, 높이가 8m인 평행사변형 모양의 논이 있어요. 이 논의 넓이는 몇 m²인가요?', answer: '200' },
    { difficulty: 'normal', topic: '문장제', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 5m, 아랫변 11m, 높이 4m인 사다리꼴 모양의 수조가 있어요. 이 수조의 넓이는 몇 m²인가요?', answer: '32' },
    { difficulty: 'normal', topic: '문장제', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선이 10m, 6m인 마름모 모양의 꽃밭이 있어요. 이 꽃밭의 넓이는 몇 m²인가요?', answer: '30' },
    { difficulty: 'normal', topic: '문장제', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 20m인 정사각형 모양의 운동장이 있어요. 이 운동장의 넓이는 몇 m²인가요?', answer: '400' },
    { difficulty: 'normal', topic: '문장제', hint: '직사각형 넓이 = 가로 × 세로. 가로 = 넓이 ÷ 세로예요.', text: '직사각형 모양의 방의 넓이가 48m²이고 세로가 6m예요. 이 방의 가로는 몇 m인가요?', answer: '8' },
    { difficulty: 'normal', topic: '문장제', hint: '평행사변형 넓이 = 밑변 × 높이. 높이 = 넓이 ÷ 밑변이에요.', text: '넓이가 90m²이고 밑변이 15m인 평행사변형 모양의 주차장이 있어요. 이 주차장의 높이는 몇 m인가요?', answer: '6' },
    { difficulty: 'normal', topic: '문장제', hint: '삼각형 넓이 = 밑변 × 높이 ÷ 2. 높이 = 넓이 × 2 ÷ 밑변이에요.', text: '넓이가 24m²이고 밑변이 6m인 삼각형 모양의 돛이 있어요. 이 돛의 높이는 몇 m인가요?', answer: '8' },
    { difficulty: 'normal', topic: '문장제', hint: '마름모 넓이 = 대각선1 × 대각선2 ÷ 2. 다른 대각선 = 넓이 × 2 ÷ 한 대각선이에요.', text: '넓이가 50cm²이고 한 대각선이 10cm인 마름모 모양의 장식품이 있어요. 다른 대각선의 길이는 몇 cm인가요?', answer: '10' },
    { difficulty: 'normal', topic: '문장제', hint: '사다리꼴 넓이 = (윗변+아랫변)×높이÷2. 아랫변을 구해요.', text: '사다리꼴 모양의 토지가 있어요. 높이 6m, 아랫변 12m이고 넓이가 60m²일 때, 윗변은 몇 m인가요?', answer: '8' },
    { difficulty: 'normal', topic: '문장제', hint: '1m² = 10000cm²이에요. 6×4=24m²를 cm²로 바꿔요.', text: '가로 6m, 세로 4m인 직사각형 마루 바닥의 넓이는 몇 cm²인가요?', answer: '240000' },

    // ── 넓이 비교 ──
    { difficulty: 'normal', topic: '넓이 비교', hint: '각 도형의 넓이를 구해서 비교해요.', text: '밑변 10cm, 높이 8cm인 삼각형과 가로 5cm, 세로 8cm인 직사각형의 넓이를 비교하면?', answer: '같다', choices: ['같다', '삼각형이 더 넓다', '직사각형이 더 넓다', '알 수 없음'] },
    { difficulty: 'normal', topic: '넓이 비교', hint: '평행사변형 넓이 = 밑변×높이, 삼각형 넓이 = 밑변×높이÷2예요.', text: '밑변 12cm, 높이 5cm인 평행사변형과 같은 밑변, 같은 높이의 삼각형이 있어요. 삼각형은 평행사변형의 몇 배의 넓이인가요?', answer: '0.5배', choices: ['0.5배', '1배', '2배', '0.25배'] },
    { difficulty: 'normal', topic: '넓이 비교', hint: '각 도형의 넓이를 구해서 비교해요.', text: '두 대각선이 8cm, 10cm인 마름모와 가로 4cm, 세로 10cm인 직사각형의 넓이를 비교하면?', answer: '같다', choices: ['같다', '마름모가 더 넓다', '직사각형이 더 넓다', '알 수 없음'] },

    // ── 심화 넓이 계산 (높은 수치) ──
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 25cm, 높이가 8cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '200' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 13cm, 10cm인 마름모의 넓이는 몇 cm²인가요?', answer: '65' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '(윗변+아랫변)×높이÷2를 계산해요.', text: '윗변 9cm, 아랫변 13cm, 높이 8cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '88' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 17cm, 높이가 6cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '51' },
    { difficulty: 'normal', topic: '평행사변형의 넓이', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 24cm, 높이가 5cm인 평행사변형의 넓이는 몇 cm²인가요?', answer: '120' },
    { difficulty: 'normal', topic: '마름모의 넓이', hint: '마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2예요.', text: '두 대각선의 길이가 각각 18cm, 8cm인 마름모의 넓이는 몇 cm²인가요?', answer: '72' },
    { difficulty: 'normal', topic: '사다리꼴의 넓이', hint: '(윗변+아랫변)×높이÷2를 계산해요.', text: '윗변 7cm, 아랫변 11cm, 높이 9cm인 사다리꼴의 넓이는 몇 cm²인가요?', answer: '81' },
    { difficulty: 'normal', topic: '삼각형의 넓이', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 22cm, 높이가 4cm인 삼각형의 넓이는 몇 cm²인가요?', answer: '44' },
    { difficulty: 'normal', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 25cm, 세로 14cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '350' },
    { difficulty: 'normal', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 15cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '225' },
    { difficulty: 'normal', topic: '직사각형의 넓이', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 30cm, 세로 20cm인 직사각형의 넓이는 몇 cm²인가요?', answer: '600' },
    { difficulty: 'normal', topic: '정사각형의 넓이', hint: '정사각형의 넓이 = 한 변 × 한 변이에요.', text: '한 변이 16cm인 정사각형의 넓이는 몇 cm²인가요?', answer: '256' },

    // ════════════════════════════════════════════════════
    // 골드: 역산·복합도형·심화 문장제 (90문제)
    // ════════════════════════════════════════════════════

    // ── 변의 길이 역산 ──
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '직사각형의 넓이 = 가로 × 세로이므로 세로 = 넓이 ÷ 가로예요.', text: '넓이가 42cm²인 직사각형의 가로가 7cm일 때, 세로는 몇 cm인가요?', answer: '6' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '가로 = 넓이 ÷ 세로예요.', text: '넓이가 90cm²인 직사각형의 세로가 9cm일 때, 가로는 몇 cm인가요?', answer: '10' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '정사각형의 넓이 = 한 변 × 한 변이에요. □ × □ = 64를 만족하는 □를 구해요.', text: '넓이가 64cm²인 정사각형의 한 변의 길이는 몇 cm인가요?', answer: '8' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '□ × □ = 144를 만족하는 □를 구해요.', text: '넓이가 144cm²인 정사각형의 한 변의 길이는 몇 cm인가요?', answer: '12' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '평행사변형의 넓이 = 밑변 × 높이이므로 밑변 = 넓이 ÷ 높이예요.', text: '넓이가 48cm²이고 높이가 6cm인 평행사변형의 밑변은 몇 cm인가요?', answer: '8' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '높이 = 넓이 ÷ 밑변이에요.', text: '넓이가 72cm²이고 밑변이 9cm인 평행사변형의 높이는 몇 cm인가요?', answer: '8' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2이므로 높이 = 넓이 × 2 ÷ 밑변이에요.', text: '넓이가 24cm²이고 밑변이 8cm인 삼각형의 높이는 몇 cm인가요?', answer: '6' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '밑변 = 넓이 × 2 ÷ 높이예요.', text: '넓이가 35cm²이고 높이가 7cm인 삼각형의 밑변은 몇 cm인가요?', answer: '10' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '마름모의 넓이 = 대각선1 × 대각선2 ÷ 2이므로 다른 대각선 = 넓이 × 2 ÷ 한 대각선이에요.', text: '넓이가 30cm²이고 한 대각선이 10cm인 마름모의 다른 대각선의 길이는 몇 cm인가요?', answer: '6' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '다른 대각선 = 넓이 × 2 ÷ 한 대각선이에요.', text: '넓이가 40cm²이고 한 대각선이 8cm인 마름모의 다른 대각선의 길이는 몇 cm인가요?', answer: '10' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '사다리꼴 넓이 = (윗변+아랫변)×높이÷2. (윗변+아랫변) = 넓이×2÷높이, 아랫변 = (합) - 윗변이에요.', text: '넓이가 35cm²이고 윗변 3cm, 높이 5cm인 사다리꼴의 아랫변은 몇 cm인가요?', answer: '11' },
    { difficulty: 'hard', topic: '변의 길이 구하기', hint: '(윗변+아랫변) = 넓이×2÷높이. 윗변 = 합 - 아랫변이에요.', text: '넓이가 60cm²이고 아랫변 12cm, 높이 8cm인 사다리꼴의 윗변은 몇 cm인가요?', answer: '3' },

    // ── 단위 변환 심화 ──
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '2.5m² = 2m² + 0.5m². 0.5m² = 5000cm²이므로 합하면 25000cm²예요.', text: '2.5m²는 몇 cm²인가요?', answer: '25000', choices: ['25000', '2500', '250000', '2500000'] },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '1.5m² = 1 × 10000 + 0.5 × 10000 = 15000cm²예요.', text: '1.5m²는 몇 cm²인가요?', answer: '15000', choices: ['15000', '1500', '150000', '1500000'] },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '3.5m² = 3.5 × 10000cm²예요.', text: '3.5m²는 몇 cm²인가요?', answer: '35000' },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '0.5m² = 0.5 × 10000cm²예요.', text: '0.5m²는 몇 cm²인가요?', answer: '5000' },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '4.8m² = 4.8 × 10000cm²예요.', text: '4.8m²는 몇 cm²인가요?', answer: '48000' },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '15000cm² ÷ 10000 = ? cm²를 m²로 바꿀 때는 10000으로 나눠요.', text: '15000cm²는 몇 m²인가요?', answer: '1.5', choices: ['1.5', '15', '150', '0.15'] },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '25000 ÷ 10000 = 2.5예요.', text: '25000cm²는 몇 m²인가요?', answer: '2.5', choices: ['2.5', '25', '250', '0.25'] },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '7500 ÷ 10000 = 0.75예요.', text: '7500cm²는 몇 m²인가요?', answer: '0.75', choices: ['0.75', '7.5', '75', '0.075'] },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '45000 ÷ 10000 = 4.5예요.', text: '45000cm²는 몇 m²인가요?', answer: '4.5' },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '0.5km² = 0.5 × 1000000m²예요.', text: '0.5km²는 몇 m²인가요?', answer: '500000', choices: ['500000', '5000', '50000', '5000000'] },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '0.3km² = 0.3 × 1000000m²예요.', text: '0.3km²는 몇 m²인가요?', answer: '300000' },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '1.5km² = 1.5 × 1000000m²예요.', text: '1.5km²는 몇 m²인가요?', answer: '1500000' },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '2.5km² = 2.5 × 1000000m²예요.', text: '2.5km²는 몇 m²인가요?', answer: '2500000' },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '750000m² ÷ 1000000 = 0.75km²예요.', text: '750000m²는 몇 km²인가요?', answer: '0.75', choices: ['0.75', '7.5', '75', '0.075'] },
    { difficulty: 'hard', topic: '넓이 단위 변환', hint: '1200000 ÷ 1000000 = 1.2예요.', text: '1200000m²는 몇 km²인가요?', answer: '1.2' },

    // ── 복합 도형의 넓이 ──
    { difficulty: 'hard', topic: '복합 도형', hint: '직사각형 전체 넓이(10×8)에서 삼각형 넓이(4×6÷2)를 빼요.', text: '가로 10cm, 세로 8cm인 직사각형에서 밑변 4cm, 높이 6cm인 삼각형을 잘라냈어요. 남은 도형의 넓이는 몇 cm²인가요?', answer: '68', choices: ['68', '80', '56', '70'] },
    { difficulty: 'hard', topic: '복합 도형', hint: '직사각형 넓이(12×9)에 삼각형 넓이(12×5÷2)를 더해요.', text: '가로 12cm, 세로 9cm인 직사각형의 위쪽에 밑변 12cm, 높이 5cm인 삼각형이 붙어 있어요. 전체 도형의 넓이는 몇 cm²인가요?', answer: '138' },
    { difficulty: 'hard', topic: '복합 도형', hint: '가로 14×세로 8에서 가로 6×세로 4 구멍을 빼요.', text: '가로 14cm, 세로 8cm인 직사각형에서 가로 6cm, 세로 4cm인 구멍을 뚫었어요. 남은 도형의 넓이는 몇 cm²인가요?', answer: '88' },
    { difficulty: 'hard', topic: '복합 도형', hint: '직사각형 넓이(8×6)에 삼각형 넓이(8×4÷2)를 더해요.', text: '가로 8cm, 세로 6cm인 직사각형의 아래에 밑변 8cm, 높이 4cm인 삼각형이 붙어 있어요. 전체 도형의 넓이는 몇 cm²인가요?', answer: '64' },
    { difficulty: 'hard', topic: '복합 도형', hint: '가로 10×세로 6에서 가로 4×세로 3 구멍을 빼요.', text: '가로 10cm, 세로 6cm인 직사각형에서 오른쪽 위 가로 4cm, 세로 3cm인 직사각형을 잘라냈어요. 남은 도형의 넓이는 몇 cm²인가요?', answer: '48' },
    { difficulty: 'hard', topic: '복합 도형', hint: '큰 정사각형(8×8)에서 작은 정사각형(3×3)을 빼요.', text: '한 변이 8cm인 정사각형에서 한 변이 3cm인 정사각형을 잘라냈어요. 남은 도형의 넓이는 몇 cm²인가요?', answer: '55' },
    { difficulty: 'hard', topic: '복합 도형', hint: '사다리꼴 넓이(윗변 6, 아랫변 10, 높이 4)에 직사각형 넓이(10×5)를 더해요.', text: '윗변 6cm, 아랫변 10cm, 높이 4cm인 사다리꼴 아래에 가로 10cm, 세로 5cm인 직사각형이 붙어 있어요. 전체 도형의 넓이는 몇 cm²인가요?', answer: '82' },
    { difficulty: 'hard', topic: '복합 도형', hint: '직사각형(15×8)에서 마름모(대각선 10cm, 6cm)를 빼요.', text: '가로 15cm, 세로 8cm인 직사각형에서 두 대각선이 10cm, 6cm인 마름모를 잘라냈어요. 남은 도형의 넓이는 몇 cm²인가요?', answer: '90' },
    { difficulty: 'hard', topic: '복합 도형', hint: '평행사변형 넓이(10×6)에 삼각형 넓이(10×4÷2)를 더해요.', text: '밑변 10cm, 높이 6cm인 평행사변형 위에 밑변 10cm, 높이 4cm인 삼각형이 붙어 있어요. 전체 도형의 넓이는 몇 cm²인가요?', answer: '80' },
    { difficulty: 'hard', topic: '복합 도형', hint: '큰 직사각형(16×10)에서 내부 직사각형(6×4)을 빼요.', text: '가로 16cm, 세로 10cm인 직사각형에서 내부의 가로 6cm, 세로 4cm인 직사각형을 빼면 남은 도형의 넓이는 몇 cm²인가요?', answer: '136' },
    { difficulty: 'hard', topic: '복합 도형', hint: '정사각형(10×10)에서 마름모(대각선 각 10cm)를 빼요. 마름모 넓이=10×10÷2=50이에요.', text: '한 변이 10cm인 정사각형에서 두 대각선이 각각 10cm인 마름모를 잘라냈어요. 남은 도형의 넓이는 몇 cm²인가요?', answer: '50' },
    { difficulty: 'hard', topic: '복합 도형', hint: '직사각형(12×8)과 직사각형(6×3), 두 넓이를 비교해요.', text: '가로 12cm, 세로 8cm인 직사각형과 가로 6cm, 세로 3cm인 직사각형이 있어요. 큰 것의 넓이는 작은 것의 몇 배인가요?', answer: '4배', choices: ['4배', '2배', '6배', '3배'] },

    // ── 심화 문장제 ──
    { difficulty: 'hard', topic: '문장제', hint: '직사각형의 넓이 = 가로 × 세로예요.', text: '가로 12m, 세로 8m인 직사각형 모양의 텃밭이 있어요. 이 텃밭의 넓이는 몇 m²인가요?', answer: '96' },
    { difficulty: 'hard', topic: '문장제', hint: '삼각형의 넓이 = 밑변 × 높이 ÷ 2예요.', text: '밑변이 6m, 높이가 4m인 삼각형 모양의 꽃밭이 있어요. 이 꽃밭의 넓이는 몇 m²인가요?', answer: '12' },
    { difficulty: 'hard', topic: '문장제', hint: '평행사변형의 넓이 = 밑변 × 높이예요.', text: '밑변이 15m, 높이가 8m인 평행사변형 모양의 공원이 있어요. 이 공원의 넓이는 몇 m²인가요?', answer: '120' },
    { difficulty: 'hard', topic: '문장제', hint: '사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2예요.', text: '윗변 5m, 아랫변 9m, 높이 4m인 사다리꼴 모양의 수영장이 있어요. 이 수영장의 넓이는 몇 m²인가요?', answer: '28' },
    { difficulty: 'hard', topic: '문장제', hint: '정사각형 한 변 = 둘레 ÷ 4. 넓이 = 한 변 × 한 변이에요.', text: '정사각형 모양의 운동장 둘레가 200m예요. 이 운동장의 넓이는 몇 m²인가요?', answer: '2500' },
    { difficulty: 'hard', topic: '문장제', hint: '직사각형 둘레 = (가로+세로)×2. 가로+세로 = 둘레÷2. 세로 = 합 - 가로예요.', text: '둘레가 34cm인 직사각형의 가로가 10cm일 때, 세로는 몇 cm인가요?', answer: '7', choices: ['7', '14', '17', '24'] },
    { difficulty: 'hard', topic: '문장제', hint: '단위를 맞춰요. 2m² = 2×10000 = 20000cm². 20000-15000 = ?', text: '넓이가 2m²인 도화지와 넓이가 15000cm²인 그림판이 있어요. 도화지가 그림판보다 몇 cm² 더 넓은가요?', answer: '5000', choices: ['5000', '50000', '500', '15000'] },
    { difficulty: 'hard', topic: '문장제', hint: '사다리꼴의 넓이 = (윗변+아랫변)×높이÷2예요.', text: '윗변 20m, 아랫변 30m, 높이 15m인 사다리꼴 모양의 논이 있어요. 이 논의 넓이는 몇 m²인가요?', answer: '375' },
    { difficulty: 'hard', topic: '문장제', hint: '마름모의 넓이 = 두 대각선의 곱 ÷ 2예요.', text: '두 대각선이 50cm, 30cm인 마름모 모양의 연이 있어요. 이 연의 넓이는 몇 cm²인가요?', answer: '750' },
    { difficulty: 'hard', topic: '문장제', hint: '직사각형 넓이 = 가로×세로. 타일 수 = 넓이예요.', text: '가로 8m, 세로 6m인 직사각형 모양의 방에 1m² 크기의 타일을 깔려고 해요. 타일은 몇 개 필요한가요?', answer: '48' },
    { difficulty: 'hard', topic: '문장제', hint: '정사각형 한 변 = √넓이. 20×20=400이에요.', text: '정사각형 모양 땅의 넓이가 400m²예요. 이 땅의 한 변의 길이는 몇 m인가요?', answer: '20' },
    { difficulty: 'hard', topic: '문장제', hint: '전체 넓이(50×30)에서 건물 넓이(20×15)를 빼요.', text: '가로 50m, 세로 30m인 운동장 안에 가로 20m, 세로 15m인 건물이 있어요. 건물을 제외한 운동장의 넓이는 몇 m²인가요?', answer: '1200' },
    { difficulty: 'hard', topic: '문장제', hint: '삼각형 넓이=밑변×높이÷2. 높이=넓이×2÷밑변이에요.', text: '넓이가 24m²이고 높이가 8m인 삼각형 모양의 돛이 있어요. 이 돛의 밑변은 몇 m인가요?', answer: '6' },
    { difficulty: 'hard', topic: '문장제', hint: '평행사변형 넓이=밑변×높이. 높이=넓이÷밑변이에요.', text: '넓이가 200m²이고 밑변이 25m인 평행사변형 모양의 주차장이 있어요. 이 주차장의 높이는 몇 m인가요?', answer: '8' },
    { difficulty: 'hard', topic: '문장제', hint: '(윗변+아랫변)×높이÷2를 계산해요.', text: '윗변 40m, 아랫변 60m, 높이 20m인 사다리꼴 모양의 토지가 있어요. 이 토지의 넓이는 몇 m²인가요?', answer: '1000' },
    { difficulty: 'hard', topic: '문장제', hint: '마름모 넓이 = 두 대각선의 곱 ÷ 2예요.', text: '두 대각선이 100m, 80m인 마름모 모양의 호수가 있어요. 이 호수의 넓이는 몇 m²인가요?', answer: '4000' },
    { difficulty: 'hard', topic: '문장제', hint: '1m² = 10000cm². 80×60=4800cm²를 m²로 바꿔요. 4800÷10000=0.48m²예요.', text: '가로 80cm, 세로 60cm인 직사각형 모양의 헝겊이 있어요. 이 헝겊의 넓이는 몇 m²인가요?', answer: '0.48' },
    { difficulty: 'hard', topic: '문장제', hint: '정사각형 한 변 = √넓이. 12×12=144. 둘레 = 12×4예요.', text: '정사각형 모양 화단의 넓이가 144m²예요. 이 화단의 둘레는 몇 m인가요?', answer: '48' },
    { difficulty: 'hard', topic: '문장제', hint: '직사각형 넓이=24m². 페인트 필요량 = 24÷3이에요.', text: '가로 6m, 세로 4m인 직사각형 모양의 벽이 있어요. 페인트 1L로 3m²를 칠할 수 있다면 이 벽을 칠하는 데 필요한 페인트는 몇 L인가요?', answer: '8' },
    { difficulty: 'hard', topic: '문장제', hint: '가로 600÷50=12개, 세로 400÷50=8개. 총 12×8개예요.', text: '가로 6m, 세로 4m인 방에 한 변이 50cm인 정사각형 타일을 빈틈없이 깔려고 해요. 타일은 모두 몇 개 필요한가요?', answer: '96' },
    { difficulty: 'hard', topic: '문장제', hint: '색종이 삼각형의 넓이 = 직사각형 넓이 ÷ 2예요.', text: '가로 15cm, 세로 12cm인 직사각형 색종이를 대각선으로 잘랐어요. 삼각형 하나의 넓이는 몇 cm²인가요?', answer: '90' },

    // ── 심화 추론 ──
    { difficulty: 'hard', topic: '심화 추론', hint: '가로+세로 = 38÷2 = 19. 세로 = 가로-3이라면 2×가로-3 = 19예요.', text: '직사각형의 둘레가 38cm이고, 세로가 가로보다 3cm 짧아요. 가로는 몇 cm인가요?', answer: '11', choices: ['11', '8', '14', '19'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '직사각형 넓이(12×8=96). 직사각형 넓이(16×6=96). 두 도형의 넓이를 비교해요.', text: '밑변 12cm, 높이 8cm인 평행사변형A와 밑변 16cm, 높이 6cm인 평행사변형B가 있어요. 두 도형의 넓이는 어떤 관계인가요?', answer: '같다', choices: ['같다', 'A가 더 크다', 'B가 더 크다', '알 수 없다'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '직사각형(12×8=96)과 정사각형(10×10=100)의 넓이를 계산해 비교해요.', text: '가로 12cm, 세로 8cm인 직사각형과 한 변이 10cm인 정사각형이 있어요. 어느 도형이 몇 cm² 더 넓은가요?', answer: '정사각형, 4cm²', choices: ['정사각형, 4cm²', '직사각형, 4cm²', '정사각형, 8cm²', '같다'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '직사각형 넓이 = 가로×세로. 가로+세로=23, 가로×세로=120. 두 수를 찾아요.', text: '직사각형의 둘레가 46cm이고 넓이가 120cm²예요. 이 직사각형의 가로와 세로는 각각 몇 cm인가요?', answer: '15cm, 8cm', choices: ['15cm, 8cm', '12cm, 10cm', '20cm, 6cm', '24cm, 5cm'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '사다리꼴 (윗변+아랫변)×높이÷2 = 48. 48×2÷(6+10) = 높이예요.', text: '넓이가 48cm²이고 윗변 6cm, 아랫변 10cm인 사다리꼴의 높이는 몇 cm인가요?', answer: '6' },
    { difficulty: 'hard', topic: '심화 추론', hint: '마름모 d1+d2=22, d1-d2=2. 더하면 2×d1=24, d1=12, d2=10이에요.', text: '마름모의 두 대각선의 합이 22cm이고 차가 2cm예요. 이 마름모의 넓이는 몇 cm²인가요?', answer: '60', choices: ['60', '48', '72', '55'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '안쪽 정사각형(6×6=36), 바깥쪽 정사각형(8×8=64). 테두리 넓이 = 64-36이에요.', text: '한 변이 6cm인 정사각형 주위에 1cm 폭의 테두리를 두를 때, 테두리의 넓이는 몇 cm²인가요?', answer: '28', choices: ['28', '24', '32', '20'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '직사각형 넓이(15×6=90). 삼각형 넓이=90. 15×밑변÷2=90이면 밑변=12예요.', text: '넓이가 같은 직사각형과 삼각형이 있어요. 직사각형의 가로 15cm, 세로 6cm이고, 삼각형의 높이가 15cm일 때 삼각형의 밑변은 몇 cm인가요?', answer: '12' },
    { difficulty: 'hard', topic: '심화 추론', hint: '평행사변형 넓이=96, 높이=8. 밑변=96÷8=12이에요.', text: '평행사변형의 넓이가 96cm²이고 높이가 8cm예요. 이 평행사변형의 밑변은 몇 cm인가요?', answer: '12' },
    { difficulty: 'hard', topic: '심화 추론', hint: 'km² ↔ m² 변환: 1km² = 1000000m²예요.', text: '어느 섬의 면적이 약 2km²예요. 이것은 몇 m²인가요?', answer: '2000000', choices: ['2000000', '200000', '20000', '2000'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '두 대각선의 합 22, 각각을 구해요. 마름모 넓이 = 대각선1×대각선2÷2예요.', text: '마름모의 한 대각선이 다른 대각선보다 4cm 짧고 넓이가 48cm²예요. 짧은 대각선은 몇 cm인가요?', answer: '8', choices: ['8', '6', '10', '12'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '정사각형 한 변=둘레÷4=15m. 넓이=15×15=225m²예요.', text: '정사각형 모양 마당의 둘레가 60m예요. 이 마당의 넓이는 몇 m²인가요?', answer: '225' },
    { difficulty: 'hard', topic: '심화 추론', hint: '직사각형 넓이=가로×세로=120. 가로-세로=2. 가로=12, 세로=10인지 확인: 12-10=2, 12×10=120 ✓', text: '넓이가 120cm²인 직사각형의 가로가 세로보다 2cm 길어요. 가로는 몇 cm인가요?', answer: '12', choices: ['12', '10', '14', '15'] },
    { difficulty: 'hard', topic: '심화 추론', hint: '사다리꼴 넓이 = (윗변+아랫변)×높이÷2. (20+아랫변)×25÷2=750이면 아랫변을 구해요.', text: '사다리꼴 모양의 토지의 넓이가 750m²이고 윗변이 20m, 높이가 25m예요. 아랫변은 몇 m인가요?', answer: '40' },
    { difficulty: 'hard', topic: '심화 추론', hint: '직사각형(40×10=400). 정사각형 넓이=400. 정사각형 한 변=20m예요.', text: '가로 40m, 세로 10m인 직사각형 모양의 땅과 넓이가 같은 정사각형 땅이 있어요. 이 정사각형의 한 변의 길이는 몇 m인가요?', answer: '20' },
    { difficulty: 'hard', topic: '심화 추론', hint: '삼각형 넓이=밑변×높이÷2. 100m×높이÷2=2500이면 높이=50m예요.', text: '밑변이 100m인 삼각형 모양 부지의 넓이가 2500m²예요. 이 부지의 높이는 몇 m인가요?', answer: '50' },
    { difficulty: 'hard', topic: '심화 추론', hint: '마름모 넓이=대각선1×대각선2÷2. 60×40÷2=1200예요.', text: '두 대각선이 60cm, 40cm인 마름모 모양의 연이 있어요. 이 연의 넓이는 몇 cm²인가요?', answer: '1200' },
  ]
};
